import React, { useState } from 'react';
import Head from 'next/head'
import Link from 'next/link'
import { Row, Col, List, Space } from 'antd'
import { CalendarOutlined, FolderOutlined, FireOutlined } from '@ant-design/icons'
import Header from '../components/Header'
import Author from '../components/Author';
import Advert from '../components/Advert'
import Footer from '../components/Footer'
import styles from '../styles/Home.module.scss'
import axios from 'axios'
import servicePath from '../config/apiUrl';
import marked from 'marked'
import highlight from 'highlight.js'
import 'highlight.js/styles/monokai-sublime.css'

const Home = (list) => {

  const [myList, setMyList] = useState(list.data)
  const renderer = new marked.Renderer()
  marked.setOptions({
      renderer: renderer,
      gfm: true,
      pedantic: false,
      sanitize: false,
      tables: true,
      breaks: true,
      smartLists: true,
      highlight: function(code) {
          return highlight.highlightAuto(code)
      }
  })
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Row className="comm-main" type="flex" justify="center">
        <Col className="comm-left" xs={24} sm={24} md={16} lg={18} xl={14}>
          <List
            className="list"
            header={<div className={styles['main-title']}>最新日志</div>}
            itemLayout='vertical'
            dataSource={myList}
            renderItem={item => (
              <List.Item>
                <div className={styles['list-title']}>
                  <Link href={{pathname: '/detail', query: {id: item.id}}}>
                    <a>{item.title}</a>
                  </Link>
                </div>
                <div className={styles['list-icon']}>
                  <Space>
                    <span>
                      <CalendarOutlined />
                      {item.createTime}
                    </span>
                    <span>
                      <FolderOutlined />
                      {item.typeName}
                    </span>
                    <span>
                      <FireOutlined />
                      {item.viewCount}
                    </span>
                  </Space>
                </div>
                <div className={styles['list-context']}
                dangerouslySetInnerHTML={{__html: marked(item.introduce)}}></div>
              </List.Item>
            )}
          >
          </List>
        </Col>
        <Col className="comm-right" xs={0} sm={0} md={7} lg={5} xl={4}>
          <Author />
          <Advert />
        </Col>
      </Row>
      <Footer />
    </div>
  )
}

Home.getInitialProps = async () => {
  const promise = new Promise((resolve) => {
    axios(servicePath.getArticleList)
      .then(res => {
        resolve(res.data)
      })
  })

  return await promise
}

export default Home