import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import { Row, Col, List, Breadcrumb } from 'antd';
import { CalendarOutlined, FolderOutlined, FireOutlined } from '@ant-design/icons'
import Header from '../components/Header';
import Author from '../components/Author';
import Advert from '../components/Advert';
import Footer from '../components/Footer';
import styles from '../styles/Home.module.scss'
import servicePath from '../config/apiUrl';
import axios from 'axios';
import Link from 'next/link';

const MyList = (list) => {
  console.info('list', list)
  const [myList, setMyList] = useState(list.data)
  useEffect(()=>{
    setMyList(list.data)
   })
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Row className="comm-main" type="flex" justify="center">
        <Col className="comm-left" xs={24} sm={24} md={16} lg={18} xl={14}>
          <div className={styles['bread-div']}>
            <Breadcrumb>
              <Breadcrumb.Item><a href="/">首页</a></Breadcrumb.Item>
              <Breadcrumb.Item>视频教程</Breadcrumb.Item>
            </Breadcrumb>
          </div>
          <List
            className="list"
            header={<div className={styles['main-title']}>最新日志</div>}
            itemLayout='vertical'
            dataSource={myList}
            renderItem={item => (
              <List.Item>
                <div className={styles['list-title']}>{item.title}</div>
                <div className={styles['list-icon']}>
                  <span>
                    <CalendarOutlined />
                    {item.createTime}
                  </span>
                  <span>
                    <FolderOutlined />
                    {item.typeName}
                  </span>
                  <span>
                    <FireOutlined />
                    {item.viewCount}
                  </span>
                </div>
                <div className={styles['list-context']}>{item.introduce}</div>
              </List.Item>
            )}
          >

          </List>
        </Col>
        <Col className="comm-right" xs={0} sm={0} md={7} lg={5} xl={4}>
          <Author />
          <Advert />
        </Col>
      </Row>
      <Footer />
    </div>
  )
}

MyList.getInitialProps = async(context) => {
  const { id } = context.query
  console.info(id)
  const promise = new Promise((resolve) => {
      axios(servicePath.getArticleListByTypeId + id)
      .then(res => {
          console.info('data', res.data)
          resolve(res.data)
      })
  });

  return await promise;
};

export default MyList